version: '3.8'

services:
  frontend:
    image: talentstream-frontend:latest
    container_name: talentstream_frontend
    build:
      context: ./src/TalentStream.Frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src/TalentStream.Frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - talentstream

  backend:
    image: talentstream-backend:latest
    container_name: talentstream_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    volumes:
      - ${PWD}/uploads:/app/wwwroot/uploads
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # ConnectionStrings (SqlDb, MongoDb, Redis)
      - ConnectionStrings__SqlDb=${SQL_CONNECTION_STRING}
      - ConnectionStrings__MongoDb=${MONGO_CONNECTION_STRING}
      - ConnectionStrings__Redis=redis:6379
      
      # MongoSettings
      - MongoSettings__DatabaseName=TalentStreamMongoDb
      
      # JWT
      - jwt__Secret=${JWT_SECRET}
      - jwt__Issuer=TalentStreamBackend
      - jwt__Audience=TalentStreamFrontend
      - jwt__ExpiryInMinutes=60
    depends_on:
      - sqlserver
      - mongodb
    networks:
      - talentstream

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_db
    user: root
    volumes:
      - sql_data:/var/opt/mssql/data
    environment:
      - ACCEPT_EULA=Y 
      - MSSQL_SA_PASSWORD=Password123!
    ports:
      - "1433:1433"
    networks:
      - talentstream

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8081:8080"
    depends_on:
      - sqlserver
    networks:
      - talentstream

  mongodb:
    image: mongo:latest
    container_name: mongodb_db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASS}
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - talentstream

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express
    ports:
      - "8082:8081"
    environment:
      - ME_CONFIG_MONGODB_URL=${MONGO_EXPRESS_URL}
    depends_on:
      - mongodb
    networks:
      - talentstream

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6380:6379"
    networks:
      - talentstream

volumes:
  sql_data:
  mongo_data:

networks:
  talentstream:
    driver: bridge